name = "Matplotlib"
description = "A simple application showing how to use Matplotlib to generate a graph and display it with PyScript."
packages = ["matplotlib", "scipy", "cbx>=1.0.0"]


[files]
"./utils.py" = ""